# Task 1

In [4]:
import numpy as np
a = np.array([[1,6],
             [2,8],
             [3,11],
             [3,10],
             [1,7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [5]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

# Task 2

In [8]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# Task 3

In [15]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]
a_centered_sp

8.0

In [16]:
covariation1 = a_centered_sp / (a.shape[0] -1)
covariation1

2.0

# Task 4

In [18]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])